name: Docker containerization application
on: workflow_dispatch
jobs:
  CI_build_Containerization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker login
        uses: docker/login-action@v3.7.0
        with:
          username: 
          password:
