name: Docker containerization application
on: workflow_dispatch
jobs:
  CI_build_Containerization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
      - name: Docker login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{vars.DOCKER_UN}}
          password: ${{secrets.DOCKER_PWD}}
      - name: Docker Build
        run: |
          docker build -t ${{vars.DOCKER_UN}}/my_java_app:latest .
      - name: Docker Push
        run: |
          docker push ${{vars.DOCKER_UN}}/my_java_app:latest
          
          
